CREATE TABLE "award_stats" (
	"level" integer NOT NULL,
	"agency_code" text NOT NULL,
	"biz_div_key" text NOT NULL,
	"amount_bucket" integer NOT NULL,
	"award_method" text NOT NULL,
	"window_from" date NOT NULL,
	"window_to" date NOT NULL,
	"n" integer NOT NULL,
	"rate_p_10" double precision,
	"rate_p_25" double precision,
	"rate_p_50" double precision,
	"rate_p_75" double precision,
	"rate_p_90" double precision,
	"rate_avg" double precision,
	"margin_n" integer NOT NULL,
	"margin_p_10" double precision,
	"margin_p_25" double precision,
	"margin_p_50" double precision,
	"margin_p_75" double precision,
	"margin_p_90" double precision,
	"margin_avg" double precision,
	"lower_limit_p_50" double precision,
	"computed_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "award_stats_level_agency_code_biz_div_key_amount_bucket_award_method_pk" PRIMARY KEY("level","agency_code","biz_div_key","amount_bucket","award_method")
);
